#!/bin/sh
#
# This script runs pre-commit and is responsible 
# for running the gitPreCommit library automatically
# to prevent merge conflicts
#
#
start "$(pwd)\libs\utilscripts\RunCreateXMLRepo.bat"
echo "XML Rebuild Complete, normalizing repository"
sleep 7
start "$(pwd)\libs\gitPreCommit.exe"
echo "gitPreCommit ran successfully, proceeding with commit"
sleep 1
git add .